= REST API Guide
신무곤(백기선님 자료를 참고했습니다.);
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `401 UnAuthorized`
| 해당 리소스에 유효한 인증 자격 증명이 없기 때문에 요청이 적용되지 않았음

| `404 Not Found`
| 요청한 리소스가 없음.

| `500 Server Internal Server error`
| 서버 내부에서 오류 발생

|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.

[[resources-index-access]]
=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::index[snippets='curl-request,http-request,http-response,links']

[[resources-login]]
== 로그인

로그인 리소스는 로그인할 때 사용한다.

[[resources-login-request]]
=== 로그인 요청

`POST` 요청을 사용해서 로그인을 요청할 수 있다.

operation::login[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']

[[resources-accounts]]
== 사용자

사용자 리소스는 사용자를 만들거나 조회할 때 사용한다.

[[resources-account-get]]
=== 사용자 개별 조회

`GET` 요청을 사용하여 개별적으로 사용자를 조회할 수 있다.

operation::get-account[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-accounts-create]]
=== 사용자 등록

`POST` 요청을 사용해서 새 사용자를 등록할 수 있다.

operation::create-account[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']

[[resources-accounts-update]]
=== 사용자 수정

`PUT` 요청을 사용해서 기존 사용자의 정보를 수정할 수 있다.

operation::update-account[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']

[[resources-accounts-delete]]
=== 사용자 삭제

`DELETE` 요청을 사용해서 기존 사용자의 정보를 삭제할 수 있다.

operation::delete-account[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-products]]
== 상품

상품 리소스는 상품을 만들거나 조회할 때 사용한다.

[[resources-products-list]]
=== 상품 목록 조회

`GET` 요청을 사용하여 서비스의 모든 상품을 조회할 수 있다.

operation::query-products[snippets='curl-request,http-request,http-response,response-headers,response-fields,links']

[[resources-get-product]]
=== 개별 상품 조회

`GET` 요청을 사용하여 서비스의 개별 상품을 조회할 수 있다.

operation::get-product[snippets='curl-request,http-request,http-response,response-headers,response-fields,links']

[[resources-products-create]]
=== 상품 등록

`POST` 요청을 사용해서 새 상품을 등록할 수 있다.

operation::create-product[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-products-update]]
=== 상품 수정

`PUT` 요청을 사용해서 기존 상품의 정보를 수정할 수 있다.

operation::update-product[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']

[[resources-products-delete]]
=== 상품 삭제

`DELETE` 요청을 사용해서 기존 상품의 정보를 삭제할 수 있다.

operation::delete-product[snippets='curl-request,http-request,http-response,response-headers,response-fields,links']

[[resources-orders]]
== 주문

주문 리소스는 주문을 만들 때 사용한다.

[[resources-orders-create]]
=== 주문 등록

`POST` 요청을 사용해서 새 주문을 등록할 수 있다.

operation::create-orders[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']